### ISSUE TITLE
SplashActivity Issue

### ISSUE THREAD

**Issue by kkangjee** [msj0319/miso_capstone_design_project#14]
1. 대기 상태에서 뒤로 갔을 때, 앱 나갔을 때 처리
3. 타 과 1명, 동일 과 2명으로 테스트하기 - V
2. 전체과 테스트 - V
3. 채팅 연결

**Comment by msj0319** [comment]
SplashActivity에서 뒤로가기 버튼 누르면, 상대방이 들어오지 않았어도 Chat 화면이 띄워지는거 맞나요

**Comment by msj0319** [comment]
전체학과 터치 시 동일하게 Splash 출력

**Comment by msj0319** [comment]
> 전체학과 터치 시 동일하게 Splash 출력

room 생성
