### ISSUE TITLE
제3자가 방을 나갈시 본인의 방의 메시지가 clear되는 issue

### ISSUE THREAD

**Issue by roycmlhj** [msj0319/miso_capstone_design_project#38]
제3자가 방을 나갈시 본인의 방의 메시지가 clear되는 issue

**Comment by kkangjee** [comment]
DB에는 데이터가 남아있다. 다만 보여지지 않는 것 같다.

**Comment by kkangjee** [comment]
![image](https://user-images.githubusercontent.com/47815477/94413438-0be27c00-01b6-11eb-89e3-c371d096206d.png)
이렇게 room 아래에 바로 메세지가 들어가게된다

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/47815477/94413452-10a73000-01b6-11eb-9aa2-e960c8b73286.png">
여기에 roomID를 제대로 받아오지 않아 경로가 삭제되는 것 같으므로 이부분을 중점적으로 확인한다

**Comment by kkangjee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [0928 Issue#38](https://trello.com/c/KO3oLmWq/2-0928-issue38)

**Comment by kkangjee** [comment]
roomID를 제대로 받아오지 못하는 이유는 방 나기 실행 시, 사용자의 randomroomid가 초기화 됨을 알았다. 이 부분을 수정해야 한다.
사용자의 randomroomid를 초기화 하는 부분은 
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/47815477/95046668-93347000-071f-11eb-9e4b-c7316327f008.png">
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/47815477/95046680-992a5100-071f-11eb-9fe9-8cc4030b944f.png">
이렇게 두 부분이다.

**Comment by roycmlhj** [comment]
그럼 lookUpRooms의 onChildRemoved의 실행이 exitRoom의 'TODO: 가져온 roomid로 rooms의 방 폭파'보다 빨라서 그런거같은데 이 TODO를 조금만 늦게 실행하거나 'TODO: users의 자신 randomRoomId 값 초기화' 뒤에서 실행해보면 되지 않을까요
